#!/bin/bash
#PBS -q workq
#PBS -l select=1:ngpus=1:gputype=irispro580
#PBS -l walltime=01:00:00
#PBS -joe

set -eu

cd $RUN_DIR || exit 2
date

case "$MODEL" in
    julia-*)
        export JULIA_EXCLUSIVE=1 # pin threads
        julia --project="$JULIA_BACKEND" -e 'import Pkg; Pkg.instantiate()'
        julia --project="$JULIA_BACKEND" "./$BENCHMARK_EXE"
        ;;
    ocl|sycl)
        "./$BENCHMARK_EXE" --device 2
        ;;    
    *)
        "./$BENCHMARK_EXE"
        ;;
esac

