#!/bin/bash
#PBS -q voltaq
#PBS -l select=1
#PBS -l walltime=00:10:00
#PBS -l place=excl
#PBS -joe

cd "$RUN_DIR" || exit 2

date

case "$MODEL" in
    omp-target|ocl|cuda|acc|kokkos)
        "./$BENCHMARK_EXE" -n 65536 -i 8
        ;;
    sycl)
        echo "$MODEL is not implemented" && exit 99
        OMP_PLACES=cores OMP_PROC_BIND=spread aprun -n 1 -d 64 -cc none "./$BENCHMARK_EXE"
        ;;
    *)
        echo "Unknown run configuration for model '$MODEL'"
        exit 1
        ;;
esac

