#!/bin/bash
#PBS -q arm
#PBS -l select=1:ncpus=64
#PBS -l walltime=00:15:00
#PBS -joe

cd "$RUN_DIR" || exit 2
date
echo "$PWD"
ldd "$BENCHMARK_EXE"

# Best performance observed when only running 16 cores per socket.
export OMP_NUM_THREADS=64
export OMP_PROC_BIND=true
export OMP_PLACES=cores

case "$MODEL" in
*)
  aprun -n 1 -d 64 -cc depth "$BENCHMARK_EXE" --list
  aprun -n 1 -d 64 -cc depth "$BENCHMARK_EXE" --deck miniBUDE/data/bm1 --wgsize 1 --ppwi all
  ;;
esac
